import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import {
  Sparkles,
  ArrowRight,
  ShieldCheck,
  RefreshCw,
  Edit3,
  Check,
  Zap,
  Target,
  Clock,
  Layers,
  HelpCircle
} from 'lucide-react';
import { useProject } from '../context/ProjectContext';
import { aiService } from '../services/aiService';
import { useToast } from '../context/ToastContext';
import { Button } from '../components/common/Button';
import { Badge } from '../components/common/Badge';

export const AIStudioPage: React.FC = () => {
  const { activeProject, updateProjectBrief, updateProjectResearch, setProjectStatus } = useProject();
  const { showToast } = useToast();
  const navigate = useNavigate();

  const brief = activeProject?.brief;
  const [isRegenerating, setIsRegenerating] = useState(false);
  const [isEditingHook, setIsEditingHook] = useState(false);
  const [hookText, setHookText] = useState(brief?.hookVariant || '');

  if (!brief) {
    return (
      <div className="max-w-3xl mx-auto p-12 text-center bg-forge-900 rounded-3xl border border-forge-800 space-y-4">
        <Sparkles className="w-12 h-12 text-purple-400 mx-auto" />
        <h2 className="text-xl font-bold text-white font-display">No Production Brief Found</h2>
        <p className="text-xs text-forge-400">Initialize a brief for this project to start the production pipeline.</p>
        <Button variant="primary" onClick={() => navigate('/create')}>
          Create Brief
        </Button>
      </div>
    );
  }

  const handleRegenerateHook = async () => {
    setIsRegenerating(true);
    try {
      const angles = await aiService.generateAngles(brief.topic);
      if (angles.length > 0) {
        const newHook = angles[0].recommendedHook;
        setHookText(newHook);
        await updateProjectBrief({ ...brief, hookVariant: newHook });
        showToast({ type: 'ai', title: 'Hook Regenerated', message: 'New pattern-interrupt hook created.' });
      }
    } finally {
      setIsRegenerating(false);
    }
  };

  const handleProceedToResearch = async () => {
    try {
      if (!activeProject?.research || !activeProject.research.sources || activeProject.research.sources.length === 0) {
        showToast({ type: 'ai', title: 'Synthesizing Research', message: 'Pulling verified sources and claims...' });
        const research = await aiService.fetchResearch(brief.topic, brief.uniqueAngle);
        await updateProjectResearch(research);
      }
      navigate('/studio/research');
    } catch (err) {
      showToast({ type: 'error', title: 'Navigation Error', message: 'Could not proceed to research workspace.' });
      navigate('/studio/research');
    }
  };

  return (
    <div className="max-w-5xl mx-auto space-y-8 pb-16">
      {/* Stage Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-forge-800">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-bold text-purple-400 font-mono uppercase tracking-wider bg-purple-950 px-2.5 py-0.5 rounded-full border border-purple-800">
              STAGE 01
            </span>
            <h1 className="text-2xl font-black text-white font-display">AI Production Brief</h1>
          </div>
          <p className="text-xs text-forge-400">
            Structured foundation blueprint generated by ClipForage AI based on your unique angle.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <Button
            variant="secondary"
            size="sm"
            onClick={handleRegenerateHook}
            isLoading={isRegenerating}
            icon={<RefreshCw className="w-3.5 h-3.5" />}
          >
            Regenerate Hook
          </Button>

          <Button
            variant="primary"
            size="sm"
            onClick={handleProceedToResearch}
            rightIcon={<ArrowRight className="w-4 h-4" />}
          >
            Approve & Review Research (Stage 02)
          </Button>
        </div>
      </div>

      {/* Grid: Angle & Rationale */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Core Angle Box */}
        <div className="md:col-span-2 bg-forge-900 border border-forge-700/80 rounded-3xl p-6 space-y-4 shadow-2xl glow-border">
          <div className="flex items-center justify-between">
            <span className="text-xs font-bold text-crimson-400 uppercase tracking-wider flex items-center gap-1.5">
              <Zap className="w-4 h-4" />
              <span>Selected Unique Angle</span>
            </span>
            <span className="text-[10px] bg-crimson-950 text-crimson-300 font-mono px-2 py-0.5 rounded border border-crimson-800">
              HIGH RETENTION
            </span>
          </div>

          <h2 className="text-lg font-bold text-white leading-relaxed">
            "{brief.uniqueAngle}"
          </h2>

          <div className="p-4 rounded-2xl bg-forge-950/80 border border-forge-800 space-y-2">
            <div className="flex items-center gap-1.5 text-xs font-bold text-purple-300">
              <Sparkles className="w-3.5 h-3.5 text-purple-400" />
              <span>Why This Angle Works:</span>
            </div>
            <p className="text-xs text-forge-300 leading-relaxed">
              {brief.whyThisAngle}
            </p>
          </div>
        </div>

        {/* Video Specs Box */}
        <div className="bg-forge-900 border border-forge-700/80 rounded-3xl p-6 space-y-4 shadow-2xl flex flex-col justify-between">
          <div className="space-y-3">
            <span className="text-xs font-bold text-forge-400 uppercase tracking-wider block pb-2 border-b border-forge-800">
              Short Specs
            </span>

            <div className="space-y-2 text-xs">
              <div className="flex justify-between">
                <span className="text-forge-400">Platform:</span>
                <span className="text-white font-bold">{brief.platform}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-forge-400">Target Duration:</span>
                <span className="text-white font-mono font-bold">{brief.duration}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-forge-400">Pacing / Tone:</span>
                <span className="text-white font-bold">{brief.tone}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-forge-400">Language:</span>
                <span className="text-white font-bold">{brief.language}</span>
              </div>
            </div>
          </div>

          <div className="p-3 rounded-xl bg-forge-950 border border-forge-800 text-[11px] text-forge-400">
            Target Audience: <strong className="text-forge-200">{brief.targetAudience}</strong>
          </div>
        </div>
      </div>

      {/* Hook Section & Alternates */}
      <div className="bg-forge-900 border border-forge-700/80 rounded-3xl p-6 sm:p-8 space-y-5 shadow-2xl">
        <div className="flex items-center justify-between pb-3 border-b border-forge-800">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-lg bg-crimson-950 text-crimson-400 border border-crimson-800">
              <Zap className="w-4 h-4" />
            </div>
            <h3 className="text-base font-bold text-white font-display">Opening Hook (0 - 5 Seconds)</h3>
          </div>

          <button
            onClick={() => setIsEditingHook(!isEditingHook)}
            className="text-xs text-crimson-400 hover:text-crimson-300 flex items-center gap-1 font-semibold"
          >
            <Edit3 className="w-3.5 h-3.5" />
            <span>{isEditingHook ? 'Done Editing' : 'Edit Hook'}</span>
          </button>
        </div>

        {isEditingHook ? (
          <textarea
            rows={3}
            value={hookText}
            onChange={(e) => {
              setHookText(e.target.value);
              updateProjectBrief({ ...brief, hookVariant: e.target.value });
            }}
            className="glass-input w-full text-sm"
          />
        ) : (
          <div className="p-4 rounded-2xl bg-crimson-950/20 border border-crimson-500/40 text-sm font-semibold text-white leading-relaxed">
            "{brief.hookVariant}"
          </div>
        )}

        {/* Alternate Hooks */}
        {brief.alternateHooks && brief.alternateHooks.length > 0 && (
          <div className="space-y-2 pt-2">
            <span className="text-[11px] font-bold text-forge-400 uppercase tracking-wider block">
              Tested Alternate Hooks (Click to swap):
            </span>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {brief.alternateHooks.map((alt, idx) => (
                <button
                  key={idx}
                  onClick={() => {
                    setHookText(alt);
                    updateProjectBrief({ ...brief, hookVariant: alt });
                    showToast({ type: 'info', title: 'Hook Swapped', message: 'Applied alternate hook.' });
                  }}
                  className="p-3 rounded-xl bg-forge-950 hover:bg-forge-850 border border-forge-800 hover:border-forge-600 text-left text-xs text-forge-300 hover:text-white transition-all"
                >
                  "{alt}"
                </button>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* 3 Core Pillars */}
      <div className="bg-forge-900 border border-forge-700/80 rounded-3xl p-6 sm:p-8 space-y-4 shadow-2xl">
        <h3 className="text-base font-bold text-white font-display pb-3 border-b border-forge-800 flex items-center gap-2">
          <Layers className="w-4 h-4 text-purple-400" />
          <span>Core Narrative Pillars (Body Architecture)</span>
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {brief.keyPillars.map((pillar, idx) => (
            <div key={idx} className="p-4 rounded-2xl bg-forge-950 border border-forge-800 space-y-2">
              <span className="text-[10px] font-mono font-bold text-purple-400 bg-purple-950 px-2 py-0.5 rounded border border-purple-800">
                PILLAR 0{idx + 1}
              </span>
              <p className="text-xs text-forge-200 font-medium leading-relaxed">{pillar}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Call to action card */}
      <div className="bg-forge-900 border border-forge-700/80 rounded-3xl p-6 flex flex-col sm:flex-row items-center justify-between gap-4">
        <div>
          <span className="text-[10px] font-bold text-forge-400 uppercase tracking-wider block">Outro CTA</span>
          <p className="text-xs text-white font-medium mt-1">"{brief.callToAction}"</p>
        </div>

        <Button variant="primary" onClick={handleProceedToResearch} rightIcon={<ArrowRight className="w-4 h-4" />}>
          Proceed to Research Workspace
        </Button>
      </div>
    </div>
  );
};
